import pywhatkit
i = 12
x = 12
while i <= 60 and x<=60:
    insultos = ['Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos','Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos','Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos','Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos','Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos','Te odio', 'tenés cara de burro', 'cuando empiezas la dieta?', 'maldita bola de fraile','gordo mantecoso','fanático de las comidas', 'portador de una talla generosa', 'poseedor de una presencia imponentenmente gorda', 'individuo de formas redondeadas','guardián de las reservas naturales de grasa','gordito','matencosito','rechonchito','boludito','tontito','burrito','hijo de puta','troll','troll x2','con los ojos cerrados juego mejor al lol q vos']
    """ print(insultos[x]) """
    pywhatkit.sendwhatmsg("+541144010813",insultos[x], 18, i, 9, True, 5)
    i = i + 1
    x = x + 1
  


